#!/usr/bin/env bash

for slot in {0..23}
do
        light_slot Front "${slot}" Off 2>&1 > /dev/null &
done

for slot in {0..11}
do
        light_slot Back "${slot}" Off 2>&1 > /dev/null &
done

# Wait for background smartctl's to complete
running=$(jobs | grep -c Running)
while [ "${running}" -ne "0" ]
do
        sleep 1
        running=$(jobs | grep -c Running)
done
