#!/usr/bin/env python3

"""
lsbackplane - List block devices attached to a storage backplane

Corrected version:
- Deduplicates multipath SAS devices by WWN
- Shows all OS block devices associated with a physical disk
- Deduplicates SES enclosures
"""

import re
import os
import sys
import time

from subprocess import Popen, PIPE, STDOUT
from shutil import which
from prettytable import PrettyTable

# Cache info
_CACHE = {}

PRINT_DEBUG = True

def Debug(input_txt):

    if PRINT_DEBUG:

        if isinstance(input_txt, dict):
            for k in input_txt.keys():
                print("DEBUG: " + str(k) + " - " + str(input_txt[k]))
        else:
            print("DEBUG: " + str(input_txt))


def SysExec(cmd):
    CACHE_TTL = 20
    now = time.time()
    if cmd in _CACHE and now - _CACHE[cmd][0] < CACHE_TTL:
        return _CACHE[cmd][1]
    result = Popen(cmd.split(), stdout=PIPE, stderr=STDOUT).communicate()[0]
    if isinstance(result, bytes):
        result = result.decode("utf-8")
    _CACHE[cmd] = (now, result)
    return result


def Bin_Requires(bin):
    bin_path = which(bin)
    if not bin_path:
        print("ERROR: Could not locate " + bin + " in the PATH")
        sys.exit(1)
    return bin_path


for bin in ("sg_ses", "sg_vpd", "lsblk", "lsscsi"):
    Bin_Requires(bin)


######################################################################
# PARSERS
######################################################################


def parse_lsblk():

    m = {}

    for line in SysExec("lsblk -O -P").splitlines():

        keyval = dict(
            re.findall(
                r'(\w+)="([^"]+)"',
                re.sub("-", "_", line)
            )
        )

        name = keyval["NAME"]
        del keyval["NAME"]

        if re.search("loop", name):
            continue

        m["/dev/" + name] = keyval

    return m


def parse_lsblk_disks():

    raw = parse_lsblk()

    disks = {}

    for k in raw.keys():

        if raw[k]["TYPE"] != "disk":
            continue

        if "HCTL" not in raw[k]:
            continue

        disks[k] = raw[k]

    return disks


def parse_lsscsi():

    m = {}

    c = 0

    for line in SysExec("lsscsi -gUN").splitlines():

        line = " ".join(line.split())

        fields = line.split()
        hctl = fields[0].strip("[]")
        type_ = fields[1]
        sas_wwn = fields[2]
        sd_dev = fields[3]
        sg_dev = fields[4]

        if sd_dev == "-":
            sd_dev = "/dev/null" + str(c)
            c += 1

        m[sd_dev] = {
            "sg_dev": sg_dev,
            "hctl": hctl,
            "sas_wwn": sas_wwn,
            "type": type_,
        }

    return m


def parse_lsscsi_disks():

    raw = parse_lsscsi()

    out = {}

    for k in raw.keys():

        if raw[k]["type"] != "disk":
            continue

        out[k] = raw[k]

    return out


def parse_lsscsi_enclosures():

    raw = parse_lsscsi()

    out = {}

    for k in raw.keys():

        if raw[k]["type"] != "enclosu":
            continue

        out[k] = raw[k]

    return out


######################################################################
# WWN AGGREGATION
######################################################################


def aggregate_physical_disks(map_lsblk):

    """
    Group all paths to the same physical disk by WWN.
    """

    physical = {}

    for sd_dev, d in map_lsblk.items():

        wwn = d.get("WWN", "") or sd_dev

        if wwn not in physical:

            physical[wwn] = {**d, "DEVICES": [sd_dev], "SG_DEVICES": []}

            if "sg_dev" in d:
                physical[wwn]["SG_DEVICES"].append(d["sg_dev"])

        else:

            physical[wwn]["DEVICES"].append(sd_dev)

            if "sg_dev" in d:
                physical[wwn]["SG_DEVICES"].append(d["sg_dev"])

            #
            # Prefer entries with enclosure data
            #
            for key in ("slot", "backplane", "bp_alias"):
                if key in d:
                    physical[wwn][key] = d[key]

    return physical


######################################################################
# ENCLOSURE HANDLING
######################################################################


def map_enclosures():

    raw = parse_lsscsi_enclosures()

    dedup = {}

    #
    # Deduplicate enclosures by SAS WWN
    #


    for sd_dev, d in raw.items():

        wwn = d["sas_wwn"]

        if wwn in dedup:
            continue

        sg_dev = d["sg_dev"]

        dedup[wwn] = dict(d)

        #
        # Determine slot count
        #

        output = SysExec("sg_ses -p aes " + str(sg_dev)).splitlines()

        num_slots = 0

        for i in output:

            if re.search("Element type: SAS expander", i):
                break

            if re.search("Element index:", i):
                num_slots += 1

        dedup[wwn]["num_slots"] = num_slots

        if num_slots == 12:
            dedup[wwn]["alias"] = "Back"

        elif num_slots == 24:
            dedup[wwn]["alias"] = "Front"

        elif num_slots == 31:
            dedup[wwn]["alias"] = "Valiant"

        elif num_slots == 36:
            dedup[wwn]["alias"] = "Unified"

        else:
            dedup[wwn]["alias"] = "Unknown"

    return dedup


def map_enclosure_slots(enclosures):

    slotmap = {}

    for enc_wwn, enc in enclosures.items():

        sg_dev = enc["sg_dev"]

        slotmap[sg_dev] = {}

        slot = ""
        sas_wwn = ""

        for line in SysExec("sg_ses -p aes " + str(sg_dev)).splitlines():

            if re.search("Element type: SAS expander", line):
                break

            if not re.search(
                "(Element index:|SAS address|target port for:)",
                line
            ):
                continue

            if re.search("attached SAS address", line):
                continue

            if re.search("Element index:", line):

                slot = line.split(":")[1].split()[0]

            if re.search("SAS address", line):

                sas_wwn = line.split(":")[1].strip()

                if sas_wwn == "0x0":
                    sas_wwn = "EMPTY"

                slotmap[sg_dev][slot] = sas_wwn

    return slotmap


######################################################################
# HUMAN FRIENDLY
######################################################################


def HumanFriendlyVendor(Vendor, Model):

    Vendor = re.sub("_", " ", Vendor)
    Model = re.sub("_", " ", Model)

    if Vendor.startswith("ST") or Model.startswith("ST"):
        return "Seagate"

    if re.search("INTEL", Model):
        return "Intel"

    if re.search("Hitachi", Model):
        return "Hitachi"

    return Vendor.strip()

def HumanFriendlyModel(Vendor, Model):

    Vendor = re.sub("_", " ", Vendor)
    Model = re.sub("_", " ", Model)

    if Model.startswith("ST"):
        return Model

    if re.search("INTEL_", model):
        return model.replace("INTEL_", "")

    if re.search("Hitachi", model):
        return model.replace("Hitachi_", "")

    return Model.strip()


def HumanFriendlySerial(Serial, Vendor, Model):

    Serial = Serial.strip()

    if Vendor == "SEAGATE":
        Serial = Serial[:8]

    if not Serial:
        return "NO_SERIAL"

    return Serial


######################################################################
# MAIN
######################################################################


map_lsblk = parse_lsblk_disks()

map_lsscsi = parse_lsscsi_disks()

#
# Augment lsblk data
#

for sd_dev, d in map_lsscsi.items():

    if sd_dev not in map_lsblk:
        continue

    map_lsblk[sd_dev]["sg_dev"] = d["sg_dev"]
    map_lsblk[sd_dev]["hctl"] = d["hctl"]
    map_lsblk[sd_dev]["lsscsi_wwn"] = d["sas_wwn"]

#
# Map enclosures
#

enclosures = map_enclosures()

slotmap = map_enclosure_slots(enclosures)

#
# Map enclosure slots onto sd devices
#

for enc_wwn, enc in enclosures.items():

    sg_dev = enc["sg_dev"]

    alias = enc["alias"]

    if sg_dev not in slotmap:
        continue

    for slot, ses_wwn in slotmap[sg_dev].items():

        if ses_wwn == "EMPTY":
            continue

        #
        # Match all paths by WWN
        #

        for sd_dev, d in map_lsblk.items():

            drive_wwn = d.get("WWN", "")

            if not drive_wwn:
                continue

            #
            # SES tends to be off-by-one
            #

            candidates = [
                hex(int(drive_wwn, 16) - 2),
                hex(int(drive_wwn, 16) - 1),
                drive_wwn,
                hex(int(drive_wwn, 16) + 1),
                hex(int(drive_wwn, 16) + 2),
            ]

            if ses_wwn in candidates:

                map_lsblk[sd_dev]["backplane"] = sg_dev
                map_lsblk[sd_dev]["slot"] = slot
                map_lsblk[sd_dev]["bp_alias"] = alias

#
# Collapse multiple sd devices into physical disks
#

physical_disks = aggregate_physical_disks(map_lsblk)

######################################################################
# OUTPUT
######################################################################

output = []

for wwn, d in physical_disks.items():

    alias_bp = str(d.get("bp_alias", "Direct"))
    slot = str(d.get("slot", "-"))

    vendor = str(d["VENDOR"]).strip()
    model = str(d["MODEL"]).strip()
    serial = str(d["SERIAL"]).strip()

    firmware = str(d["REV"]).strip()

    h_vendor = HumanFriendlyVendor(vendor, model)
    h_model = HumanFriendlyModel(vendor, model)
    h_serial = HumanFriendlySerial(serial, vendor, model)

    size = str(d["SIZE"])

    rota = str(d["ROTA"])

    rota_txt = {"1": "hd", "0": "ssd"}.get(rota, "unknown")

    media = "disk:" + rota_txt

    devs = ",".join(sorted(d["DEVICES"]))

    output.append([
        alias_bp,
        slot,
        devs,
        h_vendor,
        h_model,
        h_serial,
        firmware,
        media,
        size,
    ])

x = PrettyTable([
    "Backplane",
    "Slot",
    "Dev",
    "Vendor",
    "Model",
    "Serial",
    "Firmware",
    "Media",
    "Size",
])

x.padding_width = 1
x.align = "l"

output.sort(key=lambda r: (r[0], int(r[1]) if r[1] != "-" else -1))

for row in output:
    x.add_row(row)

print(x)
